# Generated by Django 3.2.5 on 2021-07-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_status_task_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(blank='true', upload_to='images/'),
        ),
    ]
