# Generated by Django 3.2.5 on 2021-07-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_employee_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(default='Software Engineer', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='skills',
            field=models.CharField(default='HTML, CSS, JavaScript, Django', max_length=100),
        ),
    ]
